### ISSUE TITLE
Add custom property support for Map<String, String>

### ISSUE THREAD

**Issue by fritzrichter** [OpenLocate/openlocate-ios#65]
It would be nice to let the developer add custom key/value pairs, which he wants to transmit as well via the JSON payload as Map<String,String> to provide a flexible and generic way of enhancing the payload which is sent to the configured endpoint.

**Comment by kurabi** [comment]
See https://github.com/OpenLocate/openlocate-ios/issues/65

**Comment by simonatsafegraph** [comment]
possibly means https://github.com/OpenLocate/openlocate-android/issues/59
