### ISSUE TITLE
Bug: 'Configuration' cannot be constructed because it has no accessible initializers

### ISSUE THREAD

**Issue by jsaedtler** [OpenLocate/openlocate-ios#70]
Hi tried installing the pod in a fresh, empty swift application, using a XCode 9.1. After integrating the pod as descirbed:

```
pod 'OpenLocate'
```

And adding the configuration and start in the app delegate:

```
let configuration = Configuration(url: url, headers: headers)
do {
    try OpenLocate.shared.initialize(with: configuration)
} catch {
    print(error)
}
OpenLocate.shared.startTracking()
```

I get this error message:

`AppDelegate.swift:48:29: 'Configuration' cannot be constructed because it has no accessible initializers`

and 

`AppDelegate.swift:54:41: Missing argument for parameter 'with' in call`

I was able to solve it by using the latest git version:

```
pod 'OpenLocate', :git => 'git@github.com:OpenLocate/openlocate-ios.git'
```

**Comment by kurabi** [comment]
Can you please check the Podfile.lock and check the version of OpenLocate. Let me know what it is.

If its **0.1.0**, please update to **1.0.0**
