### ISSUE TITLE
Prevent mock locations

### ISSUE THREAD

**Issue by iad24** [OpenLocate/openlocate-ios#89]
What I understand that this SDK get the device's location in an efficient way.
Does this detect or prevent mock/simulated locations?

**Comment by kurabi** [comment]
No.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iad24** [comment]
Do you have plans to implement this in the future?

**Comment by kurabi** [comment]
The solution would not client side. SafeGraph detects this server side as it’s much easier to analyze the set of data as a whole instead of each location update.

**Comment by iad24** [comment]
Im building an app when the user's current location is within a region, it will trigger some events.
Right now Im using Google Maps API for this; using GPS method.
I learned that its easy to spoof your current location using simulated locations from XCode (some more if the device is rooted) and mock locations from 3rd party Android apps. 
I also learned that one can get a separate GPS hardware and it can manipulate locations into your app.
So Im wondering if your library has the feature to detect these fake locations.
Your lib is dependent on GPS, right?

**Comment by simonatsafegraph** [comment]
I don't think OpenLocate is the right project for what you want to achieve. OpenLocate is trying to make it easier for developers to understand the places users visit, in an easy and battery-efficient way. It does this by calling location update methods already available in iOS and Android.

It isn't specifically concerned with location spoofing, as users of most mobile application aren't generally going to any lengths to spoof their locations, whether via XCode, other 3rd party apps, or GPS hardware add-ons.
